### ISSUE TITLE
Can not add an entry when the time is above 12:00

### ISSUE THREAD

**Issue by raphaelahrens** [erikh/saturn#27]
When I run

```
saturn e today at 14:00 test
```
I get the follwoing error
```
thread 'main' panicked at 'Invalid Time', /home/tant/.cargo/registry/src/index.crates.io-6f17d22bba15001f/saturn-cli-0.3.3/src/entry/parser.rs:172:54
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: saturn_cli::entry::parser::time_period
   4: saturn_cli::entry::parser::parse_time
   5: saturn_cli::entry::parser::parse_entry
   6: saturn_cli::entry::EntryParser::to_record
   7: saturn_cli::db::DB::record_entry::{{closure}}
   8: saturn::process_file::{{closure}}
   9: tokio::runtime::park::CachedParkThread::block_on
  10: tokio::runtime::context::runtime::enter_runtime
  11: tokio::runtime::runtime::Runtime::block_on
  12: saturn::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

When running `saturn e today at 14:00:00 test` the entry is created as expected.

I looked into the code and found that `parse_time` is calling `timeperiod` with `hour=14` and when I ran the command and it was after 12:00, the following code on parser.rs:183-189-  in `time_period` is called.
```
fn time_period(hour: u32, minute: u32) -> chrono::NaiveTime {
    if now().hour() >= 12 {
        pm_time(hour, minute)
    } else {
        am_time(hour, minute)
    }
}
```
and  pm_time calls parser.rs:158-169 with `twelve_howu_time(true, 14, 0)`.

```
fn twelve_hour_time(pm: bool, hour: u32, minute: u32) -> chrono::NaiveTime {
    let new_hour = if pm { 12 } else { 0 };

    time(
        if hour == 12 {
            new_hour
        } else {
            hour + new_hour
        },
        minute,
    )
}
```
This code then sets `hour` to `14+12` and the code fails, with an invalid time.

Now the question is what is the desired behavior, why does it check the current time?
Is the idea when I execute `saturn e today at 2:00` that the entry is not in the past?
This seems inconsistent because the current time should not  be considered when calling `saturn e tomorrow at 14:00 test`.

Also the function `twelve_hour_time` can be replaced by a direct call to `time(hour)` for am and `time((hour+12)%24)` for pm.

**Comment by erikh** [comment]
Hi,

First off, thanks for the in-depth analysis! It makes figuring out the bug a lot easier! :)

Second, the desired behavior is actually in the readme. It should say something along the lines of "something perceived as a 12-hour time is treated in the current time of day, 24-hour time is treated as a 24-hour amount".

The goal here was to allow you to say "8:00" at 6pm and it would correspond to "20:00" not "08:00" because of the time of day you entered it. If you really wanted 8am, you could say "08:00am" or just "8am".

I hope that helps. I'll work on this shortly, hopefully can fix it and get a release out today. Thanks for the report!

**Comment by erikh** [comment]
I committed a fix for this, I should be releasing in a little bit.
